import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import FloatingElements from "@/components/FloatingElements";
import { getWishes } from "./actions/wishes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialWishes = await getWishes();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <header className="bg-gray-800 text-white p-4 text-center mt-16">
          <h1 className="text-3xl font-semibold">Celebration of Life</h1>
          <h2 className="text-2xl mt-2">Elder David Okoobo Ovienria JP</h2>
          <p className="text-xl mt-1">1940 - 2024</p>
          <p className="mt-2">Age 84</p>
        </header>
        <main className="container mx-auto px-4 py-8">{children}</main>
        <FloatingElements initialWishes={initialWishes} />
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p>
            &copy; 2024 In Memory of Elder David Okoobo Ovienria JP. All rights
            reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}


